version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - FILES_PATH=/files
    volumes:
      - ./files:/files

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files:/usr/share/nginx/html/files:ro 
    depends_on:
      - backend
